### PR TITLE
chore: add additional logging for metadata server

### LINKED ISSUE #59: Improve Metadata Server Logging
We should provide better clarity in the pod logs on where we're actually failing when delivering metadata. Currently it only looks like: 
```
2020/09/11 14:20:06 received metadata request for uuid: 36353536-3135-5a43-3333-343956564a4e
```

### PR DESCRIPTION
**Pull request by rsmitty**
This PR adds a bunch of additional logging for the metadata server. This
is an attempt to make it clearer when we can't lookup a server or
bootstrap data for any given reason.

Will close #59 
Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>

### CODE REVIEW

**Review by andrewrynhard — COMMENTED** [review]
I feel like we could DRY this up a little more. Maybe a helper function that printed an error and reported an error?

```
func example(w http.ResponseWriter, code int, err error) {
    log.Println(err)

}
```

**Comment by smira** [comment]
+1 to what Andrew said, we could also wrap this into a function which returns and error and set http status based on error plus log the error, looks like we need specific error for 404, and everything else is just 500?

**Review by smira — APPROVED** [review]

**Pull request merged**
