### PR TITLE
Update bootstrapping.md

### PR DESCRIPTION
**Pull request by Born2Bake**
Added some changes to bootstrapping page in docs

### CODE REVIEW

**Review by andrewrynhard — DISMISSED** [review]
Thanks @Born2Bake !

**Comment by andrewrynhard** [comment]
@Born2Bake Looks like we need to get the commit in shape. Can you run:

```
git commit -s --amend -m "docs: update bootstrapping guide"
```
then
```
git push -f
```

**Comment by smira** [comment]
Looks like the build succeeded, but Drone reported failure (Sfyra tests passed).

**Pull request merged**
