### PR TITLE
chore: update Talos to 0.11.0-beta.2

### PR DESCRIPTION
**Pull request by smira**
Looks like `go` doesn't like pseudo-revisions for replaced same-worktree
folders anymore. I think we should start pushing proper tags for
`pkg/machinery/` and ignore them in the CI.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by smira** [comment]
waits for #494

**Comment by AlekSi** [comment]
That `replace` shouldn't be needed, will take a look

**Comment by smira** [comment]
> That `replace` shouldn't be needed, will take a look

Feels like something new in go behavior, it complains about fake module version.

I think proper fix is to actually start tagging machinery

**Comment by AlekSi** [comment]
Yeah, we should make a tag `pkg/machinery/v0.11.0-beta.2`

**Review by AlekSi — APPROVED** [review]

**Review by AlekSi — APPROVED** [review]

**Pull request merged**
