### PR TITLE
feat: update paths of apps

### LINKED ISSUE #424: Consistent naming of folders, images and deployments

### PR DESCRIPTION
**Pull request by rsmitty**
This PR updates the naming of the two apps that make up sidero for
consistency. It also updates things like the Makefile, Dockerfile, and
kustomize to make sure image names are the same as these app names.

Fixes #424

Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>

### CODE REVIEW

**Comment by rsmitty** [comment]
Guys, it's only 171 files changed. What could go wrong? :trollface:

**Review by andrewrynhard — APPROVED** [review]

**Comment by smira** [comment]
added a link to #424 (I think it should the issue we're closing)

**Review by smira — APPROVED** [review]
we should probably add a note to `hack/release.toml` in this PR to tell the world about this change (for anyone who got used to old names)

**Comment by rsmitty** [comment]
@smira think we're good to go now. This adds a note to release.toml that should get picked up by next release.

**Review by smira — APPROVED** [review]

**Pull request merged**
