### PR TITLE
docs: bump clusterctl from v0.3.14 to v0.3.21 in /docs/website

### PR DESCRIPTION
**Pull request by khuedoan**
Fix incompatible API version:

```
Error: installing provider "bootstrap-talos" can lead to a non functioning management cluster: the target version for the provider supports the v1alpha3 API Version of Cluster API (contract), while the management group is using v1alpha4
```

Related Cluster API documentation: https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#note-on-user-experience

Signed-off-by: Khue Doan <khuedoan98@gmail.com>

### CODE REVIEW

**Comment by khuedoan** [comment]
Is there any other steps that I need to do to before we merge this?

**Comment by rsmitty** [comment]
Sorry for the delay and thx for the update @khuedoan !

**Pull request merged**
