### PR TITLE
feat: merge Sidero HTTP endpoints under a single port

### LINKED ISSUE #402: Consolidate controller-manager and metadata-server endpoints
The goal is to have less endpoints to expose and manage

### PR DESCRIPTION
**Pull request by smira**
This merges metadata server component into `metal-controller-manager`.

iPXE server, metadata server and gRPC server share a single HTTP
endpoint now.

For the users, it means that Sidero requires only a single port to be
exposed.

Fixes #402

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Review by andrewrynhard — APPROVED** [review]

**Review by AlekSi — COMMENTED** [review]
introduction.md and resources.md still reference Metal Metadata Server

**Comment by smira** [comment]
> introduction.md and resources.md still reference Metal Metadata Server
> 
> Edit: and patching.md too

I'll get this updated in the subsequent PR, thanks

**Pull request merged**
