### PR TITLE
chore: update Sfyra for the new Talos release

### PR DESCRIPTION
**Pull request by smira**
In 0.7.0-alpha.4, asset names got changed slightly.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Review by andrewrynhard — COMMENTED** [review]
`make talos-artifacts` is broken I think.

**Comment by smira** [comment]
> `make talos-artifacts` is broken I think.

yep, thanks, fixing

**Review by andrewrynhard — DISMISSED** [review]

**Review by andrewrynhard — APPROVED** [review]

**Pull request merged**
